repos:
  # ─────────────────────────── Python formatters / linters ───────────────────────────
  - repo: https://github.com/psf/black
    rev: "24.3.0"
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length", "100"]

  # Ruff: use the already-installed system binary instead of ruff-pre-commit
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [python]
        args:
          - --line-length
          - "150"
          - --ignore
          - "E501,F841,E402,E722"

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.10.0"
  #   hooks:
  #     - id: mypy
  #       language_version: python3.12
  #       additional_dependencies:
  #         - types-requests
  #         - types-setuptools
  #         - types-paramiko
  #         - types-pytz
  #       args:
  #         - --ignore-missing-imports
  #         - --allow-untyped-defs
  #         - --install-types
  #         - --non-interactive

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer

# Default Python version for hooks that need it
default_language_version:
  python: python3.12

# Ignore generated or non-source dirs
exclude: |
  ^/(docker|docs|src/generated)/
