version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: agentzero-dev
    user: "agent:agent"
    working_dir: /workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - "8000:8000"
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      PYTHONUNBUFFERED: "1"
    networks:
      - agentzero-net
networks:
  agentzero-net:
    driver: bridge
